version: "3"
services:
  app:
    build: .
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: /usr/src/app/etm-esdl/app.py
      FLASK_ENV: development
    ports: ['5000:5000']
    volumes: ['./:/usr/src/app']
