# ESDL asset conversions for flexibility assets

# Electrolyzer
- asset: Electrolyzer
  parser: flexibility
  attribute: power
  input: capacity_of_energy_hydrogen_flexibility_p2g_electricity
  factor: 1.e-6
