# ESDL asset conversions for CHPs

- asset: CHP
  parser: subtype_capacity
  attribute: power
  type_key: CHPType
  type: UNDEFINED # do we want to support this?
  input: capacity_of_industry_chp_combined_cycle_gas_power_fuelmix
  factor: 1.e-6
- asset: CHP
  parser: subtype_capacity
  attribute: power
  type_key: CHPType
  type: STEG
  input: capacity_of_industry_chp_combined_cycle_gas_power_fuelmix
  factor: 1.e-6
- asset: CHP
  parser: subtype_capacity
  attribute: power
  type_key: CHPType
  type: GAS_TURBINE
  input: capacity_of_industry_chp_turbine_gas_power_fuelmix
  factor: 1.e-6
- asset: CHP
  parser: subtype_capacity
  attribute: power
  type_key: CHPType
  type: GAS_MOTOR
  input: capacity_of_industry_chp_engine_gas_power_fuelmix
  factor: 1.e-6

# Based on sector
- asset: CHP
  parser: volume
  attribute: power
  sector: Industry_Chemicals
  input: industry_final_demand_for_chemical_other_steam_hot_water_share
  factor: 1.e-6
- asset: CHP
  parser: volume
  attribute: power
  sector: Industry_Refineries
  input: industry_final_demand_for_chemical_refineries_steam_hot_water_share
  factor: 1.e-6
- asset: CHP
  parser: volume
  attribute: power
  sector: Industry_Other
  input: industry_aggregated_other_industry_useable_heat_share
  factor: 1.e-6
- asset: CHP
  parser: volume
  attribute: power
  sector: Industry_Food
  input: industry_final_demand_for_other_food_steam_hot_water_share
  factor: 1.e-6
- asset: CHP
  parser: volume
  attribute: power
  sector: Industry_Paper
  input: industry_final_demand_for_other_paper_steam_hot_water_share
  factor: 1.e-6
