# ESDL asset conversions for gas heaters

# Methane
- asset: GasHeater
  parser: carrier_volume
  attribute: power
  carrier: [HTLH, HTLG, RG, RTLH_ODO, RTLG_ODO, RTLH_NODO, RTLG_NODO, CH4, GM]
  sector: Industry_Chemicals
  input: industry_chemicals_other_burner_network_gas_share
  factor: 1.e-6
- asset: GasHeater
  parser: carrier_volume
  attribute: power
  carrier: [HTLH, HTLG, RG, RTLH_ODO, RTLG_ODO, RTLH_NODO, RTLG_NODO, CH4, GM]
  sector: Industry_Refineries
  input: industry_chemicals_refineries_burner_network_gas_share
  factor: 1.e-6
- asset: GasHeater
  parser: carrier_volume
  attribute: power
  carrier: [HTLH, HTLG, RG, RTLH_ODO, RTLG_ODO, RTLH_NODO, RTLG_NODO, CH4, GM]
  sector: Industry_Other
  input: industry_aggregated_other_industry_network_gas_share
  factor: 1.e-6
- asset: GasHeater
  parser: carrier_volume
  attribute: power
  carrier: [HTLH, HTLG, RG, RTLH_ODO, RTLG_ODO, RTLH_NODO, RTLG_NODO, CH4, GM]
  sector: Industry_Food
  input: industry_other_food_burner_network_gas_share
  factor: 1.e-6
- asset: GasHeater
  parser: carrier_volume
  attribute: power
  carrier: [HTLH, HTLG, RG, RTLH_ODO, RTLG_ODO, RTLH_NODO, RTLG_NODO, CH4, GM]
  sector: Industry_Paper
  input: industry_other_paper_burner_network_gas_share
  factor: 1.e-6

# Oil
- asset: GasHeater
  parser: carrier_volume
  attribute: power
  carrier: [RG, PC, HG, CO, OR, RF]
  sector: Industry_Chemicals
  input: industry_chemicals_other_burner_crude_oil_share
  factor: 1.e-6
- asset: GasHeater
  parser: carrier_volume
  attribute: power
  carrier: [RG, PC, HG, CO, OR, RF]
  sector: Industry_Refineries
  input: industry_chemicals_refineries_burner_crude_oil_share
  factor: 1.e-6
- asset: GasHeater
  parser: carrier_volume
  attribute: power
  carrier: [RG, PC, HG, CO, OR, RF]
  sector: Industry_Other
  input: industry_aggregated_other_industry_crude_oil_share
  factor: 1.e-6
- asset: GasHeater
  parser: carrier_volume
  attribute: power
  carrier: [RG, PC, HG, CO, OR, RF]
  sector: Industry_Food
  input: industry_other_food_burner_crude_oil_share
  factor: 1.e-6
- asset: GasHeater
  parser: carrier_volume
  attribute: power
  carrier: [RG, PC, HG, CO, OR, RF]
  sector: Industry_Paper
  input: industry_other_paper_burner_crude_oil_share
  factor: 1.e-6

# Hydrogen
- asset: GasHeater
  parser: carrier_volume
  attribute: power
  carrier: [H2_local, H2_Hvision, H2_new]
  sector: Industry_Chemicals
  input: industry_chemicals_other_burner_hydrogen_share
  factor: 1.e-6
- asset: GasHeater
  parser: carrier_volume
  attribute: power
  carrier: [H2_local, H2_Hvision, H2_new]
  sector: Industry_Refineries
  input: industry_chemicals_refineries_burner_hydrogen_share
  factor: 1.e-6
- asset: GasHeater
  parser: carrier_volume
  attribute: power
  carrier: [H2_local, H2_Hvision, H2_new]
  sector: Industry_Other
  input: industry_aggregated_other_industry_hydrogen_share
  factor: 1.e-6
- asset: GasHeater
  parser: carrier_volume
  attribute: power
  carrier: [H2_local, H2_Hvision, H2_new]
  sector: Industry_Food
  input: industry_other_food_burner_hydrogen_share
  factor: 1.e-6
- asset: GasHeater
  parser: carrier_volume
  attribute: power
  carrier: [H2_local, H2_Hvision, H2_new]
  sector: Industry_Paper
  input: industry_other_paper_burner_hydrogen_share
  factor: 1.e-6

# Electricity
- asset: GasHeater
  parser: carrier_volume
  attribute: power
  carrier: E
  sector: Industry_Chemicals
  input: industry_chemicals_other_heater_electricity_share
  factor: 1.e-6
- asset: GasHeater
  parser: carrier_volume
  attribute: power
  carrier: E
  sector: Industry_Other
  input: industry_aggregated_other_industry_electricity_share
  factor: 1.e-6
- asset: GasHeater
  parser: carrier_volume
  attribute: power
  carrier: E
  sector: Industry_Food
  input: industry_other_food_heater_electricity_share
  factor: 1.e-6
- asset: GasHeater
  parser: carrier_volume
  attribute: power
  carrier: E
  sector: Industry_Paper
  input: industry_other_paper_heater_electricity_share
  factor: 1.e-6
