# ESDL asset conversions for heating demand

- asset: HeatingDemand
  parser: volume
  attribute: power
  sector: Industry_Chemicals
  input: industry_useful_demand_for_chemical_other
  factor: 1.e-12
- asset: HeatingDemand
  parser: volume
  attribute: power
  sector: Industry_Aluminium
  input: industry_aluminium_production
  factor: 1.e-12
- asset: HeatingDemand
  parser: volume
  attribute: power
  sector: Industry_Metals
  input: industry_other_metals_production
  factor: 1.e-12
- asset: HeatingDemand
  parser: volume
  attribute: power
  sector: Industry_Refineries
  input: industry_useful_demand_for_chemical_refineries
  factor: 1.e-12
- asset: HeatingDemand
  parser: volume
  attribute: power
  sector: Industry_Steel
  input: industry_steel_production
  factor: 1.e-12
- asset: HeatingDemand
  parser: volume
  attribute: power
  sector: Industry_Other
  input: industry_useful_demand_for_aggregated_other
  factor: 1.e-12
- asset: HeatingDemand
  parser: volume
  attribute: power
  sector: Industry_Food
  input: industry_useful_demand_for_other_food
  factor: 1.e-12
- asset: HeatingDemand
  parser: volume
  attribute: power
  sector: Industry_Paper
  input: industry_useful_demand_for_other_paper
  factor: 1.e-12
