input_values = {
    'households_number_of_residences': { 'value': { 'value': None } },
    'households_insulation_level_apartments': { 'value': None },
    'households_insulation_level_corner_houses': { 'value': None },
    'households_insulation_level_detached_houses': { 'value': None },
    'households_insulation_level_semi_detached_houses': { 'value': None },
    'households_insulation_level_terraced_houses': { 'value': None },
    'households_heater_combined_network_gas_share': { 'value': None, 'balancing_group': 'households_heating' },
    'households_heater_district_heating_steam_hot_water_share': { 'value': None, 'balancing_group': 'households_heating' },
    'households_heater_heatpump_air_water_electricity_share': { 'value': None, 'balancing_group': 'households_heating' },
    'households_heater_heatpump_ground_water_electricity_share': { 'value': None, 'balancing_group': 'households_heating' },
    'households_heater_hybrid_heatpump_air_water_electricity_share': { 'value': None, 'balancing_group': 'households_heating' },
    'households_heater_hybrid_hydrogen_heatpump_air_water_electricity_share': { 'value': None, 'balancing_group': 'households_heating' },
    'households_heater_wood_pellets_share': { 'value': None, 'balancing_group': 'households_heating' },
    'households_heater_network_gas_share': { 'value': None, 'balancing_group': 'households_heating' },
    'households_heater_electricity_share': { 'value': None, 'balancing_group': 'households_heating' },
    'buildings_insulation_level': { 'value': None },
    'buildings_space_heater_network_gas_share': { 'value': None, 'balancing_group': 'buildings_heating' },
    'buildings_space_heater_collective_heatpump_water_water_ts_electricity_share': { 'value': None, 'balancing_group': 'buildings_heating' },
    'buildings_space_heater_heatpump_air_water_network_gas_share': { 'value': None, 'balancing_group': 'buildings_heating' },
    'buildings_space_heater_electricity_share': { 'value': None, 'balancing_group': 'buildings_heating' },
    'buildings_space_heater_wood_pellets_share': { 'value': None, 'balancing_group': 'buildings_heating' },
    'buildings_space_heater_district_heating_steam_hot_water_share': { 'value': None, 'balancing_group': 'buildings_heating' },
    'capacity_of_energy_power_wind_turbine_inland': { 'value': None },
    'capacity_of_energy_power_wind_turbine_offshore': { 'value': None },
    'flh_of_energy_power_wind_turbine_inland': { 'value': None },
    'flh_of_energy_power_wind_turbine_offshore': { 'value': None },
    'households_solar_pv_solar_radiation_market_penetration': { 'value': None },
    'buildings_solar_pv_solar_radiation_market_penetration': { 'value': None },
    'capacity_of_energy_power_solar_pv_solar_radiation': { 'value': None },
    'flh_of_solar_pv_solar_radiation': { 'value': None },
    'technical_solar_pv_efficiency': { 'value': None },
    'green_gas_total_share': { 'value': None },
}
