# Map the names of areas as used in ESDL to their ETM counterparts

Havenstad: haven_stad
GooiEnVechtstreek: RGNH03_gooi_en_vechtstreek
Hengelo: GM0164_hengelo
GM0503: GM0503_delft
# RotterdamHIC_area: GM0599_rotterdam
RotterdamHIC_area: nl
GM0716: GM0716_tholen
