# Config for conversions and inputs

# Sliders that are placed on hold will not be updated in the ETM
#  TODO: add the ON_HOLD attr to the ASSETS instead
on_hold:
  - industry_chemicals_other_burner_network_gas_share
  - industry_useful_demand_for_chemical_refineries
  - industry_useful_demand_for_chemical_other

  # These shouldn't be set when there are no power plant and/or industry demand
  # assets in the ESDL file
  - capacity_of_energy_power_combined_cycle_network_gas
  - capacity_of_energy_power_ultra_supercritical_coal
  - capacity_of_energy_power_supercritical_waste_mix
  - capacity_of_industry_chp_combined_cycle_gas_power_fuelmix
  - capacity_of_industry_chp_turbine_gas_power_fuelmix
  - capacity_of_industry_chp_engine_gas_power_fuelmix
  - industry_aluminium_production
  - industry_other_metals_production
  - industry_steel_production
  - industry_useful_demand_for_aggregated_other
  - industry_useful_demand_for_other_food
  - industry_useful_demand_for_other_paper

  # For testing purposes I turned these off - they seem to cause many problems
  - flh_of_energy_power_wind_turbine_inland
  - flh_of_solar_pv_solar_radiation
