# Config for conversions and inputs

# Sliders that are placed on hold will not be updated in the ETM
#  TODO: add the ON_HOLD attr to the ASSETS instead
on_hold:
  - industry_chemicals_other_burner_network_gas_share
  - industry_useful_demand_for_chemical_refineries
  - industry_useful_demand_for_chemical_other

  # For testing purposes I turned these off - they seem to cause many problems
  - flh_of_energy_power_wind_turbine_inland
  - flh_of_solar_pv_solar_radiation
