# How to handle distributions like the energy labels

energyLabelDistribution:
  category: bin
  attribute: energyLabel
  percentage: percentage
  inputs:
      RESIDENTIAL: [
        households_insulation_level_apartments,
        households_insulation_level_corner_houses,
        households_insulation_level_detached_houses,
        households_insulation_level_semi_detached_houses,
        households_insulation_level_terraced_houses
      ]
      UTILITY: [
        buildings_insulation_level
      ]
