# Energy labels (globally) mapped to a percentage of heat reduction
# TODO: Differentiate RESIDENTIAL to housing types

LABEL_APPP:
  RESIDENTIAL: 69.0
  UTILITY: 74.0
LABEL_APP:
  RESIDENTIAL: 60.0
  UTILITY: 74.0
LABEL_AP:
  RESIDENTIAL: 50.0
  UTILITY: 74.0
LABEL_A:
  RESIDENTIAL: 40.0
  UTILITY: 64.0
LABEL_B:
  RESIDENTIAL: 29.0
  UTILITY: 54.0
LABEL_C:
  RESIDENTIAL: 21.0
  UTILITY: 46.0
LABEL_D:
  RESIDENTIAL: 13.0
  UTILITY: 31.0
LABEL_E:
  RESIDENTIAL: 9.0
  UTILITY: 0.0
LABEL_F:
  RESIDENTIAL: 4.0
  UTILITY: 0.0
LABEL_G:
  RESIDENTIAL: 0.0
  UTILITY: 0.0
